### ISSUE TITLE
Don't show Review Schema warning if not used

### ISSUE THREAD

**Issue by subharanjanm** [axelerant/testimonials-widget#202]
> Every time I update this plugin, I see a warning at the top that Google may penalize you for using improper Schema.org markup. I already have “Enable Review Schema?” unchecked in my settings. It would be wonderful if this warning did not appear for users that have the option already unchecked. Thanks!

https://wordpress.org/support/topic/dont-show-review-schema-warning-if-not-used/

**Comment by devteam01** [comment]
**Hi 

Please help us.. We do everything we read in the forum here in https://wordpress.org/support/topic/cant-remove-review-schema-markup-notice/, Still the warning errors can't remove. 

My testimonial widget plugins is updated to Version 3.3.6 
My Wordpress version is Version 4.0.5

Please see screenshot error: http://prntscr.com/es50d9
and also we disabled check mark for review schema, but still doesn't remove. 
http://prntscr.com/es50wq

Please we need response asap. 

Thank you!**

**Comment by michael-cannon** [comment]
@saurabhsirdixit I think it's time to remove the Review schema code entirely. We might consider it a major release plus other others.

**Comment by devteam01** [comment]
Hi


Please give me instruction where will i remove the Review schema code entirely.


Please response


Thank you for reply..


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by saurabhsirdixit** [comment]
@michael-cannon Yes, I think the same. Thank you.

**Comment by saurabhsirdixit** [comment]
@devteam01 I will provide you release candidate later today in the evening. I would be happy to hear from you for more suggestion so that we can help us better and contribute more in WordPress community. Thanks.

**Comment by saurabhsirdixit** [comment]
@devteam01 I've removed the review schema code in release candidate [https://github.com/axelerant/testimonials-widget/tree/3.4.0RC1 ]from the Testimonials Widget plugin. Please download the plugin from here https://github.com/axelerant/testimonials-widget/tree/3.4.0RC1 and install it at your website. Later next week we will release the official stable version. 

I would be happy to hear from you if you still see any issue with TW plugin.

**Comment by devteam01** [comment]
Hi


Saurabh Dixit


About the installer you give to us,, how will reflect this to our site.. the old testimonials widget plugins have our client post.


If we stall the new plugins,, is there will not be replace or erase our clients post.


Please need advice we dont need to erase or replace our client post if ever we install the new plugins you give to us.


Thank you...


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by devteam01** [comment]
Hi


Finally,,


The review schema was now remove.


Thank you so much for your full cooperation


[😊]


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by saurabhsirdixit** [comment]
Hi @devteam01 

The old plugin is no longer required. Please deactivate and delete it before installing and activating the attached premium plugin. 

Further, for the updates to take effect, please save again your Settings and widget options. If that doesn't help, please try [resetting your options](https://axelerant.atlassian.net/wiki/display/WPFAQ/My+options+don%27t+work%2C+no+matter+what+I+do).

Also, there's no need to worry about data loss when replacing the plugin given that you don't have the **Remove Plugin Data on Deletion?** option checked on the Settings page, Reset tab.

## Update Plugin Using FTP

* Deactivate the current plugin
* Download and unzip files locally
* Upload the directory to your website's /wp-content/plugins/ directory
* Be sure to overwrite your existing folder contents
* Activate the plugin

## Update Plugin Using WordPress

* Uncheck "Remove Plugin Data on Deletion?" on the Settings' Reset tab and Save
* Deactivate the current plugin
* Delete the current plugin - Ignore the WordPress data deletion warning, it's always there for plugins with uninstall methods.
* Upload plugin via WordPress Admin > Plugins > Add New, Upload tab interface
* Activate the plugin

Please let me know if that helps you to move you ahead. 

Thanks
Saurabh

**Comment by devteam01** [comment]
The plugins is now working 100% the review schema is now been remove



Thank you so much!


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by saurabhsirdixit** [comment]
Removed the Review Schema code entirely from the plugin. Marking this issue closed.
